//! The `users` resource, generated by `gize make crud`.

pub mod dto;
pub mod error;
pub mod handler;
pub mod model;
pub mod repository;
pub mod routes;
pub mod service;

#[cfg(test)]
mod tests;

pub use routes::routes;
