//! Example **external** Gize plugin (ADR-008, plugin API v0).
//!
//! It builds against the public `gize_generator::plugin` API — implements [`Generator`],
//! returns a [`Plan`], and applies it through the safe [`Writer`] via `plugin::run`. Built as
//! the `gize-healthcheck` binary, so `gize healthcheck` (the subcommand fallback) runs it and
//! it inherits the whole safety model (`--dry-run`, `--force`, never clobber).
//!
//! Run it inside a generated project:
//!
//! ```text
//! gize healthcheck            # generates src/app/health.rs
//! gize healthcheck --dry-run  # preview only
//! ```

use anyhow::Result;
use gize_generator::plugin::{self, GenContext, Generator};
use gize_generator::{Options, Plan};

/// A trivial generator that adds a `/health` route module.
struct Healthcheck;

impl Generator for Healthcheck {
    fn name(&self) -> &str {
        "healthcheck"
    }

    fn plan(&self, _ctx: &GenContext, _args: &[String]) -> Result<Plan> {
        Ok(Plan::new().create("src/app/health.rs", HEALTH_RS))
    }
}

const HEALTH_RS: &str = r#"//! Health check route, generated by the gize-healthcheck plugin (ADR-008 example).

use axum::routing::get;
use axum::Router;

use crate::state::AppState;

/// A liveness probe. Wire it with `mod health;` + `.merge(health::routes())`.
pub fn routes() -> Router<AppState> {
    Router::new().route("/health", get(|| async { "ok" }))
}
"#;

fn main() -> Result<()> {
    let args: Vec<String> = std::env::args().skip(1).collect();
    let opts = Options {
        force: args.iter().any(|a| a == "--force"),
        dry_run: args.iter().any(|a| a == "--dry-run"),
    };
    let rest: Vec<String> = args.into_iter().filter(|a| !a.starts_with("--")).collect();

    let report = plugin::run(&Healthcheck, &rest, opts)?;
    println!("gize-healthcheck:\n{}", report.render(opts.dry_run));
    if !opts.dry_run {
        println!("\nWire it: add `mod health;` and `.merge(health::routes())` in src/app/mod.rs.");
    }
    Ok(())
}
