//! Templates for `gize make crud`: a full, compiling vertical slice for a resource —
//! model, DTOs, SQLx repository, service, Axum handlers, routes and a typed error.
//!
//! The repository uses SQLx's runtime query API (`query_as`), not the compile-time
//! `query!` macro, so generated projects compile without a database connection (ADR-003).
//! Placeholders (`__NAME__`, `__TABLE__`, ...) are substituted via `replace` to avoid
//! escaping the many braces in the generated Rust.

use gize_core::naming::table_name;
use gize_core::{Dialect, ModelSpec};

/// Apply the substitutions common to every CRUD file.
fn base(template: &str, model: &ModelSpec) -> String {
    let table = table_name(&model.name);
    template
        .replace("__NAME__", &model.name)
        .replace("__TABLE__", &table)
}

/// `pub name: String,` lines for the Create/Update DTOs. `String` fields get a
/// non-empty length validation so blank input is rejected with `422` rather than persisted.
fn dto_fields(model: &ModelSpec) -> String {
    model
        .fields
        .iter()
        .map(|f| {
            if matches!(f.ty, gize_core::FieldType::String) {
                format!(
                    "    #[validate(length(min = 1, message = \"must not be empty\"))]\n    pub {}: {},",
                    f.name,
                    f.ty.rust_type()
                )
            } else {
                format!("    pub {}: {},", f.name, f.ty.rust_type())
            }
        })
        .collect::<Vec<_>>()
        .join("\n")
}

/// `.bind(...)` lines. Copy scalars bind by value; `String` binds a clone. This keeps the
/// generated repository clippy-clean (no `clone_on_copy`).
fn create_binds(model: &ModelSpec) -> String {
    model
        .fields
        .iter()
        .map(|f| {
            if f.ty.is_copy() {
                format!("        .bind(input.{})", f.name)
            } else {
                format!("        .bind(input.{}.clone())", f.name)
            }
        })
        .collect::<Vec<_>>()
        .join("\n")
}

/// `mod.rs` for the resource.
pub fn mod_rs(model: &ModelSpec) -> String {
    base(
        r#"//! The `__TABLE__` resource, generated by `gize make crud`.

pub mod dto;
pub mod error;
pub mod handler;
pub mod model;
pub mod repository;
pub mod routes;
pub mod service;

#[cfg(test)]
mod tests;

pub use routes::routes;
"#,
        model,
    )
}

/// `dto.rs`: create/update request payloads.
pub fn dto_rs(model: &ModelSpec) -> String {
    let fields = dto_fields(model);
    base(
        r#"use serde::Deserialize;
use validator::Validate;

/// Payload to create a `__NAME__`.
#[derive(Debug, Deserialize, Validate)]
pub struct Create__NAME__ {
__FIELDS__
}

/// Payload to update a `__NAME__`.
#[derive(Debug, Deserialize, Validate)]
pub struct Update__NAME__ {
__FIELDS__
}
"#,
        model,
    )
    .replace("__FIELDS__", &fields)
}

/// `error.rs`: a typed error that maps to HTTP responses. The `dialect` chooses the
/// integrity-error codes mapped to 409 (ADR-015).
pub fn error_rs(model: &ModelSpec, dialect: Dialect) -> String {
    base(
        r#"use axum::http::StatusCode;
use axum::response::{IntoResponse, Response};

/// Errors returned by the `__TABLE__` resource.
#[derive(Debug)]
pub enum Error {
    NotFound,
    /// A unique constraint was violated (e.g. a duplicate key) — maps to 409.
    Conflict,
    /// A foreign-key constraint was violated (a referenced record is missing, or is still
    /// referenced by another row) — maps to 409.
    ForeignKey,
    /// Request payload failed validation — maps to 422.
    Validation(String),
    Database(sqlx::Error),
}

impl From<sqlx::Error> for Error {
    fn from(error: sqlx::Error) -> Self {
        if let sqlx::Error::RowNotFound = error {
            return Error::NotFound;
        }
        // Map database integrity violations to client errors instead of a generic 500.
__INTEGRITY_MAPPING__
        Error::Database(error)
    }
}

impl From<validator::ValidationErrors> for Error {
    fn from(errors: validator::ValidationErrors) -> Self {
        Error::Validation(errors.to_string())
    }
}

impl IntoResponse for Error {
    fn into_response(self) -> Response {
        let (status, message) = match self {
            Error::NotFound => (StatusCode::NOT_FOUND, "not found".to_string()),
            Error::Conflict => (StatusCode::CONFLICT, "already exists".to_string()),
            Error::ForeignKey => (
                StatusCode::CONFLICT,
                "a referenced record does not exist or is still in use".to_string(),
            ),
            Error::Validation(message) => (StatusCode::UNPROCESSABLE_ENTITY, message),
            Error::Database(error) => {
                // Log the detail server-side; never return a raw database error to the client
                // (it can leak schema, SQL or connection internals).
                tracing::error!(error = %error, "database error");
                (
                    StatusCode::INTERNAL_SERVER_ERROR,
                    "internal server error".to_string(),
                )
            }
        };
        (status, message).into_response()
    }
}
"#,
        model,
    )
    .replace("__INTEGRITY_MAPPING__", &dialect.integrity_error_mapping())
}

/// `repository.rs`: SQLx persistence. The `dialect` chooses the pool type, bind placeholders
/// and — on SQLite, which has no `gen_random_uuid()` — whether the app supplies `id` on insert
/// (ADR-015).
pub fn repository_rs(model: &ModelSpec, dialect: Dialect) -> String {
    let insert_cols: Vec<&str> = model.fields.iter().map(|f| f.name.as_str()).collect();
    let columns = if dialect.app_generates_id() {
        // `id` first (at $1/?1), then the fields (shifted by one).
        std::iter::once("id")
            .chain(insert_cols.iter().copied())
            .collect::<Vec<_>>()
            .join(", ")
    } else {
        insert_cols.join(", ")
    };
    let placeholder_count = model.fields.len() + if dialect.app_generates_id() { 1 } else { 0 };
    let placeholders = (1..=placeholder_count)
        .map(|i| dialect.placeholder(i))
        .collect::<Vec<_>>()
        .join(", ");
    let update_set = model
        .fields
        .iter()
        .enumerate()
        .map(|(i, f)| format!("{} = {}", f.name, dialect.placeholder(i + 1)))
        .collect::<Vec<_>>()
        .join(", ");
    let id_placeholder = dialect.placeholder(model.fields.len() + 1);
    let field_binds = create_binds(model);

    // Postgres/SQLite read the written row back with `RETURNING *` in one statement. MySQL has
    // no `RETURNING`, so it writes then re-`find`s by the app-generated `id` (ADR-015). The
    // `create`/`update` function bodies differ accordingly; `list`/`find`/`delete` are shared.
    let (create_fn, update_fn) = if dialect.supports_returning() {
        // On SQLite the app generates `id`; on Postgres the database default does.
        let id_bind = if dialect.app_generates_id() {
            "        .bind(uuid::Uuid::new_v4())\n"
        } else {
            ""
        };
        let create_binds = format!("{id_bind}{field_binds}");
        let update_binds = format!("{field_binds}\n        .bind(id)");
        (
            format!(
                r#"pub async fn create(pool: &__POOL__, input: &Create__NAME__) -> Result<__NAME__, sqlx::Error> {{
    sqlx::query_as::<_, __NAME__>(
        "INSERT INTO __TABLE__ ({columns}) VALUES ({placeholders}) RETURNING *",
    )
{create_binds}
        .fetch_one(pool)
        .await
}}"#
            ),
            format!(
                r#"pub async fn update(
    pool: &__POOL__,
    id: uuid::Uuid,
    input: &Update__NAME__,
) -> Result<__NAME__, sqlx::Error> {{
    sqlx::query_as::<_, __NAME__>(
        "UPDATE __TABLE__ SET {update_set}, updated_at = __NOW__ WHERE id = {id_placeholder} RETURNING *",
    )
{update_binds}
        .fetch_one(pool)
        .await
}}"#
            ),
        )
    } else {
        // MySQL: the app supplies `id`, so we can re-read the row after writing. `update` relies
        // on `find` (not `rows_affected`) to detect a missing row — MySQL reports 0 affected rows
        // for a no-op update of an existing row, which would otherwise look like "not found".
        (
            format!(
                r#"pub async fn create(pool: &__POOL__, input: &Create__NAME__) -> Result<__NAME__, sqlx::Error> {{
    let id = uuid::Uuid::new_v4();
    sqlx::query("INSERT INTO __TABLE__ ({columns}) VALUES ({placeholders})")
        .bind(id)
{field_binds}
        .execute(pool)
        .await?;
    find(pool, id).await
}}"#
            ),
            format!(
                r#"pub async fn update(
    pool: &__POOL__,
    id: uuid::Uuid,
    input: &Update__NAME__,
) -> Result<__NAME__, sqlx::Error> {{
    sqlx::query("UPDATE __TABLE__ SET {update_set}, updated_at = __NOW__ WHERE id = {id_placeholder}")
{field_binds}
        .bind(id)
        .execute(pool)
        .await?;
    find(pool, id).await
}}"#
            ),
        )
    };

    let assembled = r#"use sqlx::__POOL__;

use super::dto::{Create__NAME__, Update__NAME__};
use super::model::__NAME__;

pub async fn list(pool: &__POOL__) -> Result<Vec<__NAME__>, sqlx::Error> {
    sqlx::query_as::<_, __NAME__>("SELECT * FROM __TABLE__ ORDER BY created_at DESC")
        .fetch_all(pool)
        .await
}

pub async fn find(pool: &__POOL__, id: uuid::Uuid) -> Result<__NAME__, sqlx::Error> {
    sqlx::query_as::<_, __NAME__>("SELECT * FROM __TABLE__ WHERE id = __P1__")
        .bind(id)
        .fetch_one(pool)
        .await
}

__CREATE_FN__

__UPDATE_FN__

pub async fn delete(pool: &__POOL__, id: uuid::Uuid) -> Result<(), sqlx::Error> {
    let result = sqlx::query("DELETE FROM __TABLE__ WHERE id = __P1__")
        .bind(id)
        .execute(pool)
        .await?;
    if result.rows_affected() == 0 {
        return Err(sqlx::Error::RowNotFound);
    }
    Ok(())
}
"#
    .replace("__CREATE_FN__", &create_fn)
    .replace("__UPDATE_FN__", &update_fn);

    base(&assembled, model)
        .replace("__POOL__", dialect.pool_type())
        .replace("__P1__", &dialect.placeholder(1))
        .replace("__NOW__", dialect.now_expr())
}

/// `service.rs`: business layer that maps `sqlx::Error` to the module error.
pub fn service_rs(model: &ModelSpec, dialect: Dialect) -> String {
    base(
        r#"use sqlx::__POOL__;

use super::dto::{Create__NAME__, Update__NAME__};
use super::error::Error;
use super::model::__NAME__;
use super::repository;

pub async fn list(pool: &__POOL__) -> Result<Vec<__NAME__>, Error> {
    repository::list(pool).await.map_err(Error::from)
}

pub async fn find(pool: &__POOL__, id: uuid::Uuid) -> Result<__NAME__, Error> {
    repository::find(pool, id).await.map_err(Error::from)
}

pub async fn create(pool: &__POOL__, input: &Create__NAME__) -> Result<__NAME__, Error> {
    repository::create(pool, input).await.map_err(Error::from)
}

pub async fn update(
    pool: &__POOL__,
    id: uuid::Uuid,
    input: &Update__NAME__,
) -> Result<__NAME__, Error> {
    repository::update(pool, id, input).await.map_err(Error::from)
}

pub async fn delete(pool: &__POOL__, id: uuid::Uuid) -> Result<(), Error> {
    repository::delete(pool, id).await.map_err(Error::from)
}
"#,
        model,
    )
    .replace("__POOL__", dialect.pool_type())
}

/// `handler.rs`: Axum handlers wiring HTTP to the service.
pub fn handler_rs(model: &ModelSpec) -> String {
    base(
        r#"use axum::Json;
use axum::extract::{Path, State};
use axum::http::StatusCode;
use validator::Validate;

use super::dto::{Create__NAME__, Update__NAME__};
use super::error::Error;
use super::model::__NAME__;
use super::service;
use crate::state::AppState;

pub async fn list(State(state): State<AppState>) -> Result<Json<Vec<__NAME__>>, Error> {
    let items = service::list(&state.db).await?;
    Ok(Json(items))
}

pub async fn show(
    State(state): State<AppState>,
    Path(id): Path<uuid::Uuid>,
) -> Result<Json<__NAME__>, Error> {
    let item = service::find(&state.db, id).await?;
    Ok(Json(item))
}

pub async fn create(
    State(state): State<AppState>,
    Json(input): Json<Create__NAME__>,
) -> Result<(StatusCode, Json<__NAME__>), Error> {
    input.validate()?;
    let item = service::create(&state.db, &input).await?;
    Ok((StatusCode::CREATED, Json(item)))
}

pub async fn update(
    State(state): State<AppState>,
    Path(id): Path<uuid::Uuid>,
    Json(input): Json<Update__NAME__>,
) -> Result<Json<__NAME__>, Error> {
    input.validate()?;
    let item = service::update(&state.db, id, &input).await?;
    Ok(Json(item))
}

pub async fn delete(
    State(state): State<AppState>,
    Path(id): Path<uuid::Uuid>,
) -> Result<StatusCode, Error> {
    service::delete(&state.db, id).await?;
    Ok(StatusCode::NO_CONTENT)
}
"#,
        model,
    )
}

/// `routes.rs`: the resource's router. Reads (`GET`) are public; writes (`POST`/`PUT`/
/// `DELETE`) are guarded by the auth middleware (ADR-013).
pub fn routes_rs(model: &ModelSpec) -> String {
    base(
        r#"use axum::routing::{get, post};
use axum::{middleware, Router};

use super::handler;
use crate::auth::require_auth;
use crate::state::AppState;

/// Routes for the `__TABLE__` resource. Mutating routes require a valid bearer token.
pub fn routes() -> Router<AppState> {
    let public = Router::new()
        .route("/__TABLE__", get(handler::list))
        .route("/__TABLE__/:id", get(handler::show));

    let protected = Router::new()
        .route("/__TABLE__", post(handler::create))
        .route(
            "/__TABLE__/:id",
            axum::routing::put(handler::update).delete(handler::delete),
        )
        .route_layer(middleware::from_fn(require_auth));

    public.merge(protected)
}
"#,
        model,
    )
}

/// `tests.rs`: placeholder until database-backed integration tests land (`gize-testing`).
pub fn tests_rs(model: &ModelSpec) -> String {
    base(
        r#"//! Tests for the `__TABLE__` resource.
//!
//! CRUD is best exercised end-to-end against a test database; `gize-testing` will provide
//! helpers for that. This placeholder keeps the module green until then.

#[test]
fn placeholder() {}
"#,
        model,
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    fn product() -> ModelSpec {
        ModelSpec::parse(
            "Product",
            &[
                "name:String".to_string(),
                "price:i32".to_string(),
                "active:bool".to_string(),
            ],
        )
        .unwrap()
    }

    #[test]
    fn dto_has_all_fields() {
        let out = dto_rs(&product());
        assert!(out.contains("pub struct CreateProduct"));
        assert!(out.contains("pub struct UpdateProduct"));
        assert!(out.contains("pub name: String,"));
        assert!(out.contains("pub price: i32,"));
        assert!(out.contains("pub active: bool,"));
    }

    #[test]
    fn repository_builds_sql() {
        let out = repository_rs(&product(), Dialect::Postgres);
        assert!(out.contains("INSERT INTO products (name, price, active) VALUES ($1, $2, $3)"));
        assert!(
            out.contains(
                "SET name = $1, price = $2, active = $3, updated_at = now() WHERE id = $4"
            )
        );
        assert!(out.contains(".bind(input.name.clone())"));
        assert!(out.contains(".bind(id)"));
    }

    #[test]
    fn repository_follows_the_sqlite_dialect() {
        let out = repository_rs(&product(), Dialect::Sqlite);
        assert!(out.contains("use sqlx::SqlitePool;"));
        // SQLite has no gen_random_uuid(): the app supplies id, columns/placeholders shift.
        assert!(
            out.contains("INSERT INTO products (id, name, price, active) VALUES (?1, ?2, ?3, ?4)")
        );
        assert!(out.contains(".bind(uuid::Uuid::new_v4())"));
        assert!(out.contains("WHERE id = ?1")); // find/delete use ?1, not $1
        assert!(out.contains("updated_at = strftime"));
    }

    #[test]
    fn handler_and_routes_reference_resource() {
        let handler = handler_rs(&product());
        assert!(handler.contains("Json<Vec<Product>>"));
        let routes = routes_rs(&product());
        assert!(routes.contains("\"/products\""));
        assert!(routes.contains("\"/products/:id\""));
    }
}
