//! Template for the generated `src/app/openapi.rs`: serves the OpenAPI spec and an API
//! reference UI (ADR-010). The spec itself is `openapi.json` at the project root, generated
//! from `gize.toml` and refreshed by `gize sync`.

/// `src/app/openapi.rs` — routes serving `/openapi.json` and `/docs`.
pub fn module_rs() -> String {
    r###"//! OpenAPI spec + docs, generated by Gize (ADR-010).
//!
//! The spec is `openapi.json` at the project root, generated from `gize.toml`. Run
//! `gize sync` after adding resources to refresh it.

use axum::response::{Html, IntoResponse};
use axum::routing::get;
use axum::Router;

use crate::state::AppState;

/// The generated OpenAPI document, embedded at compile time.
const SPEC: &str = include_str!("../../openapi.json");

async fn spec() -> impl IntoResponse {
    ([("content-type", "application/json")], SPEC)
}

async fn docs() -> Html<&'static str> {
    Html(DOCS_HTML)
}

const DOCS_HTML: &str = r##"<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>API reference</title>
  </head>
  <body>
    <script id="api-reference" data-url="/openapi.json"></script>
    <script src="https://cdn.jsdelivr.net/npm/@scalar/api-reference"></script>
  </body>
</html>"##;

/// Routes serving the OpenAPI spec (`/openapi.json`) and the reference UI (`/docs`).
pub fn routes() -> Router<AppState> {
    Router::new()
        .route("/openapi.json", get(spec))
        .route("/docs", get(docs))
}
"###
    .to_string()
}
